version: "2"
services:
  worker:
    build: ../../.
    volumes:
      - ../../:/usr/src/app
    environment:
      - DJANGO_CONFIGURATION=Dev
      - PSQL_HOST=postgres
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
  reactjs:
    build: ../../.
    volumes:
      - ../../:/usr/src/app
    working_dir: /usr/src/app/eventol/front
    ports:
      - "3000:3000"
  redis:
    image: redis:4.0.2
    expose:
      - "6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    volumes:
      - ./elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    expose:
      - "9300"
      - "9200"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=eventol
      - POSTGRES_DB=eventol
    expose:
      - "5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
