# Generated by Django 4.2 on 2026-03-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0057_update_activity_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to presentation, video, blog, or other external resource', max_length=500, null=True, verbose_name='External Link'),
        ),
    ]
